CREATE TABLE "mytable" (
  "CREATE TABLE Hospital (" text
);

INSERT INTO "mytable" ("CREATE TABLE Hospital (")
VALUES
('Hospital_Id serial NOT NULL PRIMARY KEY'),
('Hospital_Name VARCHAR (100) NOT NULL'),
('Hospital_Type VARCHAR (10)'),
(');'),
('INSERT INTO Hospital (Hospital_Id'),
('VALUES'),
('(1'),
('(2'),
('(3'),
('(4'),
('CREATE TABLE Doctor ('),
('Doctor_Id serial NOT NULL PRIMARY KEY'),
('Doctor_Name VARCHAR (100) NOT NULL'),
('Hospital_Id serial NOT NULL'),
('Joining_Date DATE NOT NULL'),
('Speciality VARCHAR (100) NOT NULL'),
('Salary INTEGER NOT NULL'),
('Experience SMALLINT'),
(');'),
('INSERT INTO Doctor (Doctor_Id'),
('VALUES'),
('(''101'''),
('(''102'''),
('(''103'''),
('(''104'''),
('(''105'''),
('(''106'''),
('(''107'''),
('(''108'''),
('(''109'''),
('(''110'''),
('(''111'''),
('(''112'''),
('(''113'''),
('(''114'''),
('(''115'''),
('(''116'''),
('(''117'''),
('(''118'''),
('SELECT * FROM Doctor WHERE Doctor_Id = %s'),
('UPDATE Doctor SET Experience = %s WHERE Doctor_Id = %s'),
('SELECT Doctor_Id'),
('FROM Doctor WHERE Doctor_Id = %s'),
('DELETE FROM Doctor WHERE Doctor_Id = %s');
